# Generated by Django 4.1.4 on 2022-12-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OwnerLastFakIdModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_fak_id",
                    models.CharField(
                        blank=True, default="0000000001", max_length=10, null=True
                    ),
                ),
                (
                    "last_pr_id",
                    models.CharField(
                        blank=True, default="0000000001", max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mol", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("tel", models.CharField(blank=True, max_length=13, null=True)),
                ("http", models.URLField(blank=True, null=True)),
                ("bulstat", models.IntegerField()),
                ("idnum", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="owner_image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnerBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("kod", models.CharField(max_length=8)),
                ("smetka", models.CharField(max_length=30)),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owner.ownermodel",
                    ),
                ),
            ],
        ),
    ]
