# Generated by Django 4.1.4 on 2022-12-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_remove_ownermodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_image'),
        ),
    ]
