# Generated by Django 4.1.4 on 2022-12-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("name_short", models.CharField(max_length=5)),
                ("dop", models.BooleanField(default=False)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FloorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                ("r_bed", models.IntegerField(default=1)),
                ("d_bed", models.IntegerField(blank=True, null=True)),
                ("allow_one_only", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12, unique=True)),
                ("description", models.TextField()),
                (
                    "floor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.floormodel",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.roomtypemodel",
                    ),
                ),
            ],
        ),
    ]
