# Generated by Django 4.1.4 on 2022-12-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_bedmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypemodel',
            name='name_short',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtypemodel',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
