# Generated by Django 4.1.4 on 2022-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roommodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
