# Generated by Django 4.1.4 on 2022-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mol', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('bulstat', models.IntegerField()),
                ('idnum', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'firm',
                'managed': True,
            },
        ),
    ]
