# Generated by Django 4.1.4 on 2023-01-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
