# Generated by Django 4.1.4 on 2023-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0002_firmmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmodel',
            name='bulstat',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='firmmodel',
            name='idnum',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
