# Generated by Django 4.1.4 on 2023-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contragents', '0003_alter_firmmodel_bulstat_alter_firmmodel_idnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmmodel',
            name='bulstat',
            field=models.CharField(max_length=9),
        ),
    ]
